
--
-- Table structure for table `companies`
--

DROP TABLE IF EXISTS `companies`;

CREATE TABLE `companies` (
  `symbol` varchar(5) NOT NULL,
  `name` varchar(38) NOT NULL,
  `sector` varchar(27) NOT NULL,
  `subindustry` varchar(47) NOT NULL,
  `address` varchar(29) NOT NULL,
  `exchange` varchar(23) NOT NULL,
  `website` varchar(38) NOT NULL,
  `description` varchar(2048) DEFAULT NULL,
  `latitude` float DEFAULT NULL,
  `longitude` float DEFAULT NULL,
  `financials` longtext,
  PRIMARY KEY (`symbol`)
);


--
-- Dumping data for table `companies`
--

LOCK TABLES `companies` WRITE;

INSERT INTO `companies` VALUES ('A','Agilent Technologies Inc','Health Care','Health Care Equipment','Santa Clara, California','New York Stock Exchange','http://www.agilent.com','Agilent Technologies Inc is engaged in life sciences, diagnostics and applied chemical markets. The company provides application focused solutions that include instruments, software, services and consumables for the entire laboratory workflow.',37.3249,-121.999,'{\"years\":[2019,2018,2017],\"revenue\":[5163000,4914000,4472000],\"earnings\":[1071000,316000,684000],\"assets\":[9452000,8541000,8426000],\"liabilities\":[4704000,3974000,3595000]}');
INSERT INTO `companies` VALUES ('AAP','Advance Auto Parts','Consumer Discretionary','Automotive Retail','Roanoke, Virginia','New York Stock Exchange','https://shop.advanceautoparts.com','Advance Auto Parts Inc is an automotive aftermarket parts provider serving professional installers, DIY (do-it-yourself) customer and independently-owned operators.',37.3175,-79.9582,'{\"years\":[2019,2018,2017],\"revenue\":[9709003,9580554,9373784],\"earnings\":[486896,423847,475505],\"assets\":[11248525,9040648,8482301],\"liabilities\":[7699444,5489835,5067105	]}');
INSERT INTO `companies` VALUES ('AAPL','Apple Inc.','Information Technology','Computer Hardware','Cupertino, California','Nasdaq Global Select','http://www.apple.com','Apple Inc is designs, manufactures and markets mobile communication and media devices and personal computers, and sells a variety of related software, services, accessories, networking solutions and third-party digital content and applications.',37.3347,-122.009,'{\"years\":[2019,2018,2017],\"revenue\":[260174000,265595000,229234000],\"earnings\":[55256000,59531000,48351000],\"assets\":[338516000,365725000,375319000],\"liabilities\":[248028000,258578000,241272000]}');
INSERT INTO `companies` VALUES ('ABC','AmerisourceBergen Corp','Health Care','Health Care Distributors','Chesterbrook, Pennsylvania','New York Stock Exchange','http://www.amerisourcebergen.com','AmerisourceBergen Corp is a pharmaceutical services company. It provides drug distribution and related healthcare services and solutions to pharmacy, physician, and manufacturer customers based in the United States and Canada.',40.0686,-75.4683,NULL);
INSERT INTO `companies` VALUES ('ABT','Abbott Laboratories','Health Care','Health Care Equipment','North Chicago, Illinois','New York Stock Exchange','http://www.abbottinvestor.com','Abbott Laboratories is a health care company that manufactures medical devices, blood glucose monitoring kits, nutritional healthcare products, diagnostic products and equipment, and branded generic drugs.',42.3384,-87.8345,'{\"years\":[2019,2018,2017],\"revenue\":[31904000,30578000,27390000],\"earnings\":[3687000,2368000,477000],\"assets\":[67887000,67173000,76250000],\"liabilities\":[36799000,36649000,45353000]}');
INSERT INTO `companies` VALUES ('ACN','Accenture plc','Information Technology','IT Consulting & Other Services','Dublin, Ireland','New York Stock Exchange','http://www.accenture.com','Accenture PLC is a professional service company. It provides consulting, technology and outsourcing services to Communications, Media and Technology, Financial services, Health and Public service, Products and Resources segments.',53.3393,-6.23868,NULL);
INSERT INTO `companies` VALUES ('ADBE','Adobe Systems Inc','Information Technology','Application Software','San Jose, California','Nasdaq Global Select','http://www.adobe.com','Adobe Systems Inc offers a line of software and services for content creation and the measurement of digital advertising and marketing. Its software applications includes Photoshop and Lightroom, Adobe Analytics, Media Optimizer and Campaign Manager.',37.331,-121.894,'{\"years\":[2019,2018,2017],\"revenue\":[11171297,9030008,7301505],\"earnings\":[2951458,2590774,1693954],\"assets\":[18768682,14535556,12707114],\"liabilities\":[18768682,14535556,12707114]}');
INSERT INTO `companies` VALUES ('ADI','Analog Devices, Inc.','Information Technology','Semiconductors','Norwood, Massachusetts','Nasdaq Global Select','http://www.analog.com','Analog Devices Inc is engaged in the semiconductor industry. Its business involves designing, manufacturing and marketing of high-performance analog, mixed-signal and digital signal processing integrated circuits used in all types of electronic equipment.',42.2105,-71.1806,'{\"years\":[2019,2018,2017],\"revenue\":[5991065,6200942,5107503],\"earnings\":[1363011,1495432,727259],\"assets\":[20449779,21141294,7970278],\"liabilities\":[9461239,10979754,2804660]}');
INSERT INTO `companies` VALUES ('ADM','Archer-Daniels-Midland Co','Consumer Staples','Agricultural Products','Decatur, Illinois','New York Stock Exchange','http://www.adm.com','Archer-Daniels Midland Co is a major processor of oilseeds, corn, wheat, and other agricultural commodities. The company\'s end products include vegetable oil and meal, corn sweeteners, flour, feed ingredients, and ethanol.',39.8653,-88.8987,'{\"years\":[2019,2018,2017],\"revenue\":[64656000,64341000,60828000],\"earnings\":[1379000,1810000,1595000],\"assets\":[43997000,40833000,39963000],\"liabilities\":[24714000,21788000,21588000]}');
INSERT INTO `companies` VALUES ('ADP','Automatic Data Processing','Information Technology','Internet Software & Services','Roseland, New Jersey','Nasdaq Global Select','http://www.adp.com','Automatic Data Processing Inc is a provider of miscellaneous business solutions. Its business includes provision of technology-based outsourcing solutions to employers, vehicle retailers and manufacturers.',40.8156,-74.3102,'{\"years\":[2019,2018,2017],\"revenue\":[14110200,13274200,12372000],\"earnings\":[2292800,1884900,1787800],\"assets\":[41887700,38849100,37180000],\"liabilities\":[36487800,34113200,33203000]}');
INSERT INTO `companies` VALUES ('ADS','Alliance Data Systems','Information Technology','Data Processing & Outsourced Services','Plano, Texas','New York Stock Exchange','http://www.alliancedata.com','Alliance Data Systems Corp provides marketing, loyalty, and credit solutions in the United States, Canada, and other countries. The business activity of the group is functioned through LoyaltyOne, Epsilon, and Card service segment.',33.0817,-96.8233,'{\"years\":[2019,2018,2017],\"revenue\":[5581300,5666600,5474700],\"earnings\":[278000,963100,788700],\"assets\":[26494800,30387700,30684800],\"liabilities\":[24906500,28055600,28829500]}');
INSERT INTO `companies` VALUES ('ADSK','Autodesk Inc','Information Technology','Application Software','San Rafael, California','Nasdaq Global Select','http://www.autodesk.com','Autodesk Inc is engaged in the software industry. It develops software for a number of markets such as construction and media.',38.0054,-122.531,'{\"years\":[2019,2018,2017],\"revenue\":[2569800,2056600,2031000],\"earnings\":[-80800,-557300,-523800],\"assets\":[4729200,4113600,4798100],\"liabilities\":[4940100,4369600,4064500]}');
INSERT INTO `companies` VALUES ('AEP','American Electric Power','Utilities','Electric Utilities','Columbus, Ohio','New York Stock Exchange','http://www.aep.com','American Electric Power Co Inc is a regulated utilities operator. The company generates, transmits and distributes electricity to more than 5 million retail customers across over 10 states in the United States of America.',39.9627,-83.0029,'{\"years\":[2019,2018,2017],\"revenue\":[15561400,16195700,15424900],\"earnings\":[1921100,1923800,2139000],\"assets\":[4077800,4113900,4253100],\"liabilities\":[56151500,49665600,46430200]}');
INSERT INTO `companies` VALUES ('AES','AES Corp','Utilities','Independent Power Producers & Energy Traders','Arlington, Virginia','New York Stock Exchange','http://www.aes.com','The AES Corp is a power generation and utility company. It is engaged in providing affordable, sustainable energy through its diverse portfolio of thermal and renewable generation facilities as well as distribution businesses.',38.8797,-77.1127,NULL);
INSERT INTO `companies` VALUES ('AFL','AFLAC Inc','Financials','Life & Health Insurance','Columbus, Georgia','New York Stock Exchange','http://www.aflac.com','Aflac Inc is a general business holding company and acts as a management company. It offers supplemental health and life insurance in the U.S. and Japan.',32.467,-84.9639,'{\"years\":[2019,2018,2017],\"revenue\":[22307000,21758000,21667000],\"earnings\":[3304000,2920000,4604000],\"assets\":[152768000,140406000,137217000],\"liabilities\":[123809000,116944000,112619000	]}');
INSERT INTO `companies` VALUES ('AIG','American International Group, Inc.','Financials','Property & Casualty Insurance','New York, New York','New York Stock Exchange','http://www.aig.com','American International Group Inc is an insurance company. The company through its subsidiaries provides property casualty insurance, life insurance, retirement products, mortgage insurance and other financial services in the United States and abroad.',40.7064,-74.0051,NULL);
INSERT INTO `companies` VALUES ('AIZ','Assurant Inc','Financials','Multi-line Insurance','New York, New York','New York Stock Exchange','http://www.assurant.com','Assurant Inc is a provider of specialized insurance products and related services in North America and selected other international markets.',40.7078,-74.0089,NULL);
INSERT INTO `companies` VALUES ('AJG','Arthur J. Gallagher & Co.','Financials','Insurance Brokers','Itasca, Illinois','New York Stock Exchange','http://www.ajg.com','Arthur J. Gallagher & Co is engaged in providing insurance brokerage and consulting services and third-party claims settlement and administration services to both domestic and international entities.',41.9883,-88.0159,NULL);
INSERT INTO `companies` VALUES ('AKAM','Akamai Technologies Inc','Information Technology','Internet Software & Services','Cambridge, Massachusetts','Nasdaq Global Select','https://www.akamai.com','Akamai Technologies Inc is a United States based company which provides cloud services for delivering, optimizing and securing online content and business applications over the Internet.',42.365,-71.0889,NULL);
INSERT INTO `companies` VALUES ('ALL','Allstate Corp','Financials','Property & Casualty Insurance','Northfield Township, Illinois','New York Stock Exchange','http://www.allstate.com','Allstate Corp, through its subsidiaries, is primarily engaged in the property-liability insurance business and the life insurance, retirement and investment products business. It offers its products in the United States and Canada.',42.101,-87.8711,NULL);
INSERT INTO `companies` VALUES ('ALXN','Alexion Pharmaceuticals','Health Care','Biotechnology','Cheshire, Connecticut','Nasdaq Global Select','http://www.alexion.com','Alexion Pharmaceuticals Inc is a biopharmaceutical company. It is engaged in serving patients with severe and ultra-rare disorders through the development and commercialization of life-transforming therapeutic products.',41.5478,-72.9174,NULL);
INSERT INTO `companies` VALUES ('AMAT','Applied Materials Inc','Information Technology','Semiconductor Equipment','Santa Clara, California','Nasdaq Global Select','http://www.appliedmaterials.com','Applied Materials Inc is a supplier of semiconductor manufacturing equipment. It provides manufacturing equipment, services and software to the semiconductor, flat panel display, solar photovoltaic and related industries.',37.38,-121.98,NULL);
INSERT INTO `companies` VALUES ('AMD','Advanced Micro Devices Inc','Information Technology','Semiconductor','Santa Clara, California','Nasdaq Global Select','http://www.amd.com','Advanced Micro Devices Inc designs and produces microprocessors and low-power processor solutions for the computer, communications, and consumer electronics industries.',37.3829,-121.97,'{\"years\":[2019,2018,2017],\"revenue\":[6731000,6475000,5253000],\"earnings\":[341000,337000,-33000],\"assets\":[6028000,4556000,3552000],\"liabilities\":[3201000,3290000,2956000]}');
INSERT INTO `companies` VALUES ('AME','AMETEK Inc','Industrials','Electrical Components & Equipment','Berwyn, Pennsylvania','New York Stock Exchange','http://www.ametek.com','AMETEK Inc is a manufacturer of electronic instruments and electromechanical devices with operations in North America, Europe, Asia and South America.',40.0619,-75.4635,NULL);
INSERT INTO `companies` VALUES ('AMGN','Amgen Inc','Health Care','Biotechnology','Thousand Oaks, California','Nasdaq Global Select','http://www.amgen.com','Amgen Inc is a U.S. based biotechnology company, with historical expertise in renal disease and cancer supportive care products. The firm discovers, develops, manufactures and delivers human therapeutics.',34.1922,-118.919,NULL);
INSERT INTO `companies` VALUES ('AMT','American Tower Corp A','Real Estate','Specialized REITs','Boston, Massachusetts','New York Stock Exchange','http://www.americantower.com','American Tower Corp is a real estate investment trust and an owner, operator and developer of multitenant communications real estate. The company leases the space of communications sites to wireless service providers, and wireless data providers.',42.3465,-71.0799,NULL);
INSERT INTO `companies` VALUES ('AMZN','Amazon.com Inc','Consumer Discretionary','Internet & Direct Marketing Retail','Seattle, Washington','Nasdaq Global Select','http://www.amazon.com','Amazon.com Inc is an online retailer. The Company sells its products through the website which provides services, such as advertising services and co-branded credit card agreements. It also offers electronic devices like Kindle e-readers and Fire tablets.',47.6223,-122.336,'{\"years\":[2019,2018,2017],\"revenue\":[280522000,232887000,177866000],\"earnings\":[11588000,10073000,3033000],\"assets\":[225248000,162648000,131310000],\"liabilities\":[163188000,119099000,103601000]}');
INSERT INTO `companies` VALUES ('AON','Aon plc','Financials','Insurance Brokers','London, United Kingdom','New York Stock Exchange','http://www.aon.com','Aon PLC acts as a provider of risk management services, insurance and reinsurance brokerage, human resource consulting, and outsourcing solutions. The commercial risk solutions generate maximum revenue.',51.5138,-0.082233,NULL);
INSERT INTO `companies` VALUES ('AOS','A.O. Smith-Corp','Industrials','Building Products','Milwaukee, Wisconsin','New York Stock Exchange','http://www.aosmith.com','A.O. Smith Corp manufactures and markets water heaters and boilers, for residential and commercial end markets. The Company has two reporting segments; North America and Rest of World.',43.1515,-88.0516,NULL);
INSERT INTO `companies` VALUES ('APA','Apache Corporation','Energy','Oil & Gas Exploration & Production','Houston, Texas','New York Stock Exchange','http://www.apachecorp.com','Apache Corp is engaged in the oil and gas sector. As an independent energy company, its activities include exploration, development and production of natural gas, crude oil and natural gas liquids.',29.7449,-95.4616,NULL);
INSERT INTO `companies` VALUES ('APC','Anadarko Petroleum Corp','Energy','Oil & Gas Exploration & Production','The Woodlands, Texas','New York Stock Exchange','http://www.anadarko.com','Anadarko Petroleum Corp is engaged in the exploration and production of oil and natural gas. Its asset base includes conventional and unconventional properties in the U.S. and deep-water oil and gas projects in the Gulf of Mexico and Africa.',30.1607,-95.4538,NULL);
INSERT INTO `companies` VALUES ('APH','Amphenol Corp','Information Technology','Electronic Components','Wallingford, Connecticut','New York Stock Exchange','http://www.amphenol.com','Amphenol Corp is engaged in the field of electronic components. It designs and manufactures electrical, electronic and fiber optic connectors, interconnect systems and coaxial and flat-ribbon cables.',41.4609,-72.8331,NULL);
INSERT INTO `companies` VALUES ('ATVI','Activision Blizzard','Information Technology','Home Entertainment Software','Santa Monica, California','Nasdaq Global Select','http://www.activisionblizzard.com','Activision Blizzard is a developer and publisher of interactive entertainment content and services. It develops and distributes content and services on video game consoles, personal computers, and mobile devices.',34.0198,-118.452,'{\"years\":[2019,2018,2017],\"revenue\":[6489000,7500000,7017000],\"earnings\":[1503000,1848000,273000],\"assets\":[19845000,17890000,18668000],\"liabilities\":[7040000,6498000,9206000]}');
INSERT INTO `companies` VALUES ('AVGO','Broadcom','Information Technology','Semiconductors','San Jose, California','Nasdaq Global Select','https://www.broadcom.com','Broadcom Inc is engaged in designing, developing and supplying analog and digital semiconductor connectivity solutions. Its product portfolio serves wired infrastructure, wireless communications, enterprise storage and industrial and other end markets.',37.4005,-121.93,NULL);
INSERT INTO `companies` VALUES ('AWK','American Water Works Company Inc','Utilities','Water Utilities','Voorhees, New Jersey','New York Stock Exchange','http://www.amwater.com','Broadcom Inc is engaged in designing, developing and supplying analog and digital semiconductor connectivity solutions. Its product portfolio serves wired infrastructure, wireless communications, enterprise storage and industrial and other end markets.',39.9488,-75.1308,NULL);
INSERT INTO `companies` VALUES ('AXP','American Express Co','Financials','Consumer Finance','New York, New York','New York Stock Exchange','http://www.americanexpress.com','American Express Co is a payments, network and travel company. It provides charge and credit card products, travel services, network services, stored value products, loans, and other products and services to businesses and individuals.',40.7134,-74.0153,'{\"years\":[2019,2018,2017],\"revenue\":[4702000,43281000,38990000],\"earnings\":[6759000,6921000,2748000],\"assets\":[198321000,188602000,181196000],\"liabilities\":[175250000,166312000,162935000]}');
INSERT INTO `companies` VALUES ('AYI','Acuity Brands Inc','Industrials','Electrical Components & Equipment','Atlanta, Georgia','New York Stock Exchange','http://www.acuitybrands.com','Acuity Brands Inc through its subsidiaries provides lighting and building management solutions and services for commercial, institutional, industrial, and residential applications. Its products include luminaires, lighting controls and components etc.',33.7863,-84.3837,NULL);
INSERT INTO `companies` VALUES ('BA','Boeing Company','Industrials','Aerospace & Defense','Chicago, Illinois','New York Stock Exchange','http://www.boeing.com','Boeing Co designs, develops, manufactures, sells, services and supports commercial jetliners, military aircraft, satellites, missile defense, human space flight and launch systems and services.',41.8839,-87.6387,'{\"years\":[2019,2018,2017],\"revenue\":[76559000,101127000,94005000],\"earnings\":[-636000,10460000,8458000],\"assets\":[133625000,117359000,112362000],\"liabilities\":[142242000,117020000,110706000]}');
INSERT INTO `companies` VALUES ('BAC','Bank of America Corp','Financials','Banks','Charlotte, North Carolina','New York Stock Exchange','http://www.bankofamerica.com','Bank of America Corporation is a bank holding and a financial holding company. The company provides financial products and services to people, companies and institutional investors.',35.2273,-80.8419,'{\"years\":[2019,2018,2017],\"revenue\":[113589000,109627000,99466000],\"earnings\":[27430000,28147000,18232000],\"assets\":[2434079000,2354507000,2281234000],\"liabilities\":[2169269000,2089182000,2014088000]}');
INSERT INTO `companies` VALUES ('BAX','Baxter International Inc.','Health Care','Health Care Equipment','Deerfield, Illinois','New York Stock Exchange','http://www.baxter.com','Baxter International Inc operates in the healthcare industry. It provides renal and hospital products such as infusion systems and systems, parenteral nutrition therapies, and biosurgery products.',42.16,-87.8785,NULL);
INSERT INTO `companies` VALUES ('BBT','BB&T Corporation','Financials','Banks','Winston-Salem, North Carolina','New York Stock Exchange','http://www.bbt.com','BB&T Corporation is a financial holding company. It is a regional banking company with a presence primarily in the Southeastern United States. The company provides a range of banking services, and loans to businesses and consumers.',36.0956,-80.2451,NULL);
INSERT INTO `companies` VALUES ('BBY','Best Buy Co. Inc.','Consumer Discretionary','Computer & Electronics Retail','Richfield, Minnesota','New York Stock Exchange','http://www.bestbuy.com','Best Buy Co Inc is a U.S transnational consumer electronics company. Its products include tablets and computers, televisions, mobile phones, large and small appliances, entertainment products, digital imaging and related accessories.',44.8641,-93.305,'{\"years\":[2019,2018,2017],\"revenue\":[42879000,42151000,39403000],\"earnings\":[1464000,1000000,1228000],\"assets\":[8870000,9829000,10516000],\"liabilities\":[9595000,9437000,9147000]}');
INSERT INTO `companies` VALUES ('BIIB','BIOGEN IDEC Inc.','Health Care','Biotechnology','Weston, Massachusetts','Nasdaq Global Select','http://www.biogen.com','Biogen Inc is a biopharmaceutical company. It is engaged in discovering, developing, manufacturing and delivering therapies to patients for the treatment of neurological, rare and autoimmune diseases.',42.3707,-71.2745,NULL);
INSERT INTO `companies` VALUES ('BK','The Bank of New York Mellon Corp.','Financials','Banks','New York, New York','New York Stock Exchange','https://www.bnymellon.com','Bank of New York Mellon Corporation is an investment company. The company provides investment management, investment services and wealth management that help institutions and individuals succeed in markets all over the world',40.7143,-74.0118,NULL);
INSERT INTO `companies` VALUES ('BLK','BlackRock','Financials','Asset Management & Custody Banks','New York, New York','New York Stock Exchange','http://www.blackrock.com','BlackRock Inc provides investment management services to institutional clients and to individual investors. Its products include single- and multi-asset portfolios investing in equities, fixed income, alternatives and money market instruments.',40.7517,-73.9796,NULL);
INSERT INTO `companies` VALUES ('BLL','Ball Corp','Materials','Metal & Glass Containers','Broomfield, Colorado','New York Stock Exchange','http://www.ball.com','Ball Corp is the world\'s largest metal can manufacturer. The company primarily serves the North American food can market with its packaging products and the US defense industry by offering various components used in the space mission.',39.9111,-105.149,NULL);
INSERT INTO `companies` VALUES ('BMY','Bristol-Myers Squibb','Health Care','Health Care Distributors','New York, New York','New York Stock Exchange','http://www.bms.com','Bristol-Myers Squibb Co is a biopharmaceutical company. It discovers, develops, licenses, manufactures, markets, distributes and sells biopharmaceutical products.',40.7581,-73.9728,NULL);
INSERT INTO `companies` VALUES ('BWA','BorgWarner','Consumer Discretionary','Auto Parts & Equipment','Auburn Hills, Michigan','New York Stock Exchange','http://www.borgwarner.com','BorgWarner Inc is a supplier of auto parts. Its products comprise technologies for combustion, hybrid and electric vehicles. The company operates in two business segments that are Engine and Drivetrain. The Engine segment generates maximum revenue.',42.6459,-83.211,NULL);
INSERT INTO `companies` VALUES ('C','Citigroup Inc.','Financials','Banks','New York, New York','New York Stock Exchange','http://www.citigroup.com','Citigroup Inc is a financial-services company with business spanning more than 100 countries. Its core business is providing banking services, investment banking, cash management, and various other products and services.',40.7248,-74.0348,'{\"years\":[2019,2018,2017],\"revenue\":[74286000,72854000,71449000],\"earnings\":[19401000,18045000,-6798000],\"assets\":[1951158000,1917383000,1842465000],\"liabilities\":[1757212000,1720309000,1640793000]}');
INSERT INTO `companies` VALUES ('CAH','Cardinal Health Inc.','Health Care','Health Care Distributors','Dublin, Ohio','New York Stock Exchange','http://www.cardinal.com','Cardinal Health Inc is a healthcare services company. It provides services and products for hospital systems, pharmacies, ambulatory surgery centers, clinical laboratories and physician offices.',40.1091,-83.121,NULL);
INSERT INTO `companies` VALUES ('CAT','Caterpillar Inc.','Industrials','Construction & Farm Machinery & Heavy Trucks','Peoria, Illinois','New York Stock Exchange','http://www.caterpillar.com','Caterpillar Inc caters to the farming industry in the United States. It manufactures construction & mining equipment, diesel & natural gas engines, industrial gas turbines and diesel-electric locomotives.',40.6917,-89.5884,'{\"years\":[2019,2018,2017],\"revenue\":[53800000,54722000,45462000],\"earnings\":[6093000,6147000,754000],\"assets\":[78453000,78509000,76962000],\"liabilities\":[63865000,64470000,63265000]}');
INSERT INTO `companies` VALUES ('CB','Chubb Limited','Financials','Property & Casualty Insurance','Zurich, Switzerland','New York Stock Exchange','https://www.chubb.com','Chubb Ltd provides commercial and personal property and casualty insurance, personal accident and supplemental health insurance (A&H), reinsurance and life insurance to a diverse group of clients.',47.3695,8.5361,NULL);
INSERT INTO `companies` VALUES ('CBS','CBS Corp.','Consumer Discretionary','Broadcasting & Cable TV','New York, New York','New York Stock Exchange','http://www.cbscorporation.com','CBS Corp is a media company. It operates businesses within the media and entertainment industries, including cable networks, content production and distribution, television and radio stations, Internet-based businesses, and consumer publishing.',40.7612,-73.9787,NULL);
INSERT INTO `companies` VALUES ('CCL','Carnival Corp.','Consumer Discretionary','Hotels, Resorts & Cruise Lines','Miami, Florida','New York Stock Exchange','http://www.carnivalcorp.com','Carnival Corp is leisure travel company providing vacations to major cruise destinations across the world. It operates over 100 cruise ships brands including Carnival Cruise Lines, Holland America, Princess Cruise, Seabourn and fathom, and Cunard Line.',25.8073,-80.3357,NULL);
INSERT INTO `companies` VALUES ('CDNS','Cadence Design Systems','Information Technology','Application Software','San Jose, California','Nasdaq Global Select','http://www.cadence.com','Cadence Design Systems Inc develops system design enablement solutions that are used to design whole electronics systems, complex integrated circuits, and electronic devices. The firm provides maintenance services for its software, hardware, and others.',37.3958,-121.919,NULL);
INSERT INTO `companies` VALUES ('CHD','Church & Dwight','Consumer Staples','Household Products','Ewing, New Jersey','New York Stock Exchange','http://www.churchdwight.com','Church & Dwight Co Inc is engaged in the household products industry. It manufactures and markets personal care products under brands like Oxiclean, Spinbrush, First Response and Trojan.',40.2869,-74.7871,NULL);
INSERT INTO `companies` VALUES ('CHTR','Charter Communications','Consumer Discretionary','Cable & Satellite','Stamford, Connecticut','Nasdaq Global Select','https://www.spectrum.com','Charter Communications Inc is a providers of cable services in the United States. The company offers entertainment, information and communications solutions to residential and commercial customers.',41.1234,-73.5264,NULL);
INSERT INTO `companies` VALUES ('CI','CIGNA Corp.','Health Care','Managed Health Care','Philadelphia, Pennsylvania','New York Stock Exchange','http://www.cigna.com','Cigna Corp operates in the healthcare industry. It provides medical, dental, disability, life and accident insurance products.',39.9516,-75.1674,NULL);
INSERT INTO `companies` VALUES ('CMG','Chipotle Mexican Grill','Consumer Discretionary','Restaurants','Newport Beach, California','New York Stock Exchange','http://www.chipotle.com','Chipotle Mexican Grill Inc together with its subsidiaries operates Chipotle Mexican Grill restaurants, which serves a menu of burritos, tacos, burrito bowls and salads, made using fresh ingredients.',33.6183,-117.872,NULL);
INSERT INTO `companies` VALUES ('CNC','Centene Corporation','Health Care','Managed Health Care','St Louis, Missouri','New York Stock Exchange','http://www.centene.com','Centene Corp offers healthcare plans to United States government sponsored healthcare programs. The company primarily focuses on uninsured individuals and helps them access care facilities, and social services through government subsidized programs.',38.6495,-90.3345,NULL);
INSERT INTO `companies` VALUES ('CNP','CenterPoint Energy','Utilities','MultiUtilities','Houston, Texas','New York Stock Exchange','http://www.centerpointenergy.com','CenterPoint Energy Inc owns and operates a portfolio of energy-related businesses. The company primarily provides transmission and distribution services and has natural gas distribution systems in the United States.',29.7475,-95.3086,NULL);
INSERT INTO `companies` VALUES ('COF','Capital One Financial','Financials','Consumer Finance','Tysons Corner, Virginia','New York Stock Exchange','http://www.capitalone.com','Capital One Financial Corp operates in the financial domain. Through its banking and non-banking subsidiaries, it markets financial products and services.',38.9151,-77.2206,NULL);
INSERT INTO `companies` VALUES ('CPB','Campbell Soup','Consumer Staples','Packaged Foods & Meats','Camden, New Jersey','New York Stock Exchange','http://www.campbellsoupcompany.com','Campbell Soup Co operates in the packaged foods industry. The products within its scope include meals and beverages, biscuits and snacks.',39.9391,-75.108,NULL);
INSERT INTO `companies` VALUES ('CRM','Salesforce.com','Information Technology','Internet Software & Services','San Francisco, California','New York Stock Exchange','http://www.salesforce.com','Salesforce.com Inc is a software-as-a-service company that provides enterprise cloud computing solutions, offering social and mobile cloud apps and platform services, as well as professional services to facilitate the adoption of its solutions.',37.7898,-122.397,'{\"years\":[2019,2018,2017],\"revenue\":[13282000,10540000,8437000],\"earnings\":[1110000,360000,323000],\"assets\":[10683000,9584000,5996827],\"liabilities\":[15132000,11608000,10084796]}');
INSERT INTO `companies` VALUES ('CSCO','Cisco Systems','Information Technology','Networking Equipment','San Jose, California','Nasdaq Global Select','http://www.cisco.com','Cisco Systems Inc is a supplier of data networking equipment and software. Its products include routers, switches, access equipment, and security and network management software which allow data communication among dispersed computer networks.',37.4102,-121.927,'{\"years\":[2019,2018,2017],\"revenue\":[11621000,110000,9609000],\"earnings\":[6093000,6147000,754000],\"assets\":[97793000,108784000,129818000],\"liabilities\":[64222000,65580000,63681000]}');
INSERT INTO `companies` VALUES ('CTAS','Cintas Corporation','Industrials','Diversified Support Services','Mason, Ohio','Nasdaq Global Select','http://www.cintas.com','Cintas Corp is a provider of corporate identity uniforms. It products include rental and sale of entrance mats, mops, shop towels, and restroom supplies. The company also offers safety supplies, fire-suppression systems maintenance and others.',39.3412,-84.283,NULL);
INSERT INTO `companies` VALUES ('CTL','CenturyLink Inc','Telecommunications Services','Integrated Telecommunications Services','Monroe, Louisiana','New York Stock Exchange','http://www.centurylink.com','CenturyLink Inc operates as a telecommunications company in the United States. It provides broadband, voice and wireless services to consumers and businesses across the country.',32.589,-92.0665,NULL);
INSERT INTO `companies` VALUES ('CTXS','Citrix Systems','Information Technology','Internet Software & Services','Fort Lauderdale, Florida','Nasdaq Global Select','http://www.citrix.com','Citrix Systems Inc provides virtualization, networking and cloud infrastructure solutions. It provides a complete and integrated portfolio of application delivery, virtualization, mobility, network delivery and file sharing solutions.',26.2043,-80.1542,'{\"years\":[2019,2018,2017],\"revenue\":[3010564,2973903,2824686],\"earnings\":[681813,575667,-20719],\"assets\":[4388926,5136049,5820176],\"liabilities\":[3551270,4576420,4827715]}');
INSERT INTO `companies` VALUES ('CVX','Chevron Corp.','Energy','Integrated Oil & Gas','San Ramon, California','New York Stock Exchange','http://www.chevron.com','Chevron Corp engages in the exploration, production, and refining operations worldwide. Its oil refineries are spread across the United States, South Africa, and Asia with an approximate capacity of 2 million barrels of oil a day.',37.7587,-121.959,NULL);
INSERT INTO `companies` VALUES ('D','Dominion Resources','Utilities','Electric Utilities','Richmond, Virginia','New York Stock Exchange','http://www.dominionenergy.com','Dominion Energy Inc is a producer and transporter of energy. It manages its daily operations through three operating segments namely Dominion Virginia Power of DVP, Dominion Energy and Dominion Generation.',37.538,-77.4399,NULL);
INSERT INTO `companies` VALUES ('DAL','Delta Air Lines','Industrials','Airlines','Atlanta, Georgia','New York Stock Exchange','http://www.delta.com','Delta Air Lines Inc provides scheduled air transportation for passengers and cargo throughout the United States and across the world.',33.6565,-84.4218,NULL);
INSERT INTO `companies` VALUES ('DG','Dollar General','Consumer Discretionary','General Merchandise Stores','Goodlettsville, Tennessee','New York Stock Exchange','http://www.dollargeneral.com','Dollar General Corp is a discount retailer in the United States. It offers a selection of merchandise, including consumables, seasonal, home products and apparel.',36.3092,-86.7001,NULL);
INSERT INTO `companies` VALUES ('DIS','The Walt Disney Company','Consumer Discretionary','Broadcasting & Cable TV','Burbank, California','New York Stock Exchange','http://www.disney.com','Walt Disney Co together with its subsidiaries is a diversified worldwide entertainment company with operations in four business segments: Media Networks, Parks and Resorts, Studio Entertainment, and Consumer Products & Interactive Media.',34.1568,-118.325,'{\"years\":[2019,2018,2017],\"revenue\":[69570000,59434000,55137000],\"earnings\":[11054000,12598000,8980000],\"assets\":[193984000,98598000,95789000],\"liabilities\":[100095000,45766000,50785000]}');
INSERT INTO `companies` VALUES ('DISCA','Discovery Communications-A','Consumer Discretionary','Cable & Satellite','Silver Spring, Maryland','Nasdaq Global Select','http://www.discoverycommunications.com','Discovery Inc formerly known as Discovery Communications Inc is a media and entertainment company. It provides programming across multiple distribution platforms.',38.9955,-77.0283,'{\"years\":[2019,2018,2017],\"revenue\":[11144000,10553000,6873000],\"earnings\":[2069000,594000,-337000],\"assets\":[33735000,32550000,22555000],\"liabilities\":[22211000,22448000,17945000]}');
INSERT INTO `companies` VALUES ('DISH','Dish Network','Consumer Discretionary','Cable & Satellite','Meridian, Colorado','Nasdaq Global Select','http://www.dish.com','DISH Network Corp provides a direct broadcast satellite subscription television service in the United States. It offers pay-TV services under the DISH brand and the Sling brand.',39.6121,-105.023,NULL);
INSERT INTO `companies` VALUES ('DRI','Darden Restaurants','Consumer Discretionary','Restaurants','Orlando, Florida','New York Stock Exchange','http://www.darden.com','Darden Restaurants Inc is engaged in the food & beverage industry. Its primary occupation involves the operation of dining restaurants under trade names such as Olive Garden, LongHorn Steakhouse and Bahama Breeze.',28.418,-81.4248,NULL);
INSERT INTO `companies` VALUES ('DUK','Duke Energy','Utilities','Electric Utilities','Charlotte, North Carolina','New York Stock Exchange','http://www.duke-energy.com','Duke Energy Corp operates regulates utilities across the US. The company distributes electricity and gas to its customers and engages in three segments: electric utilities and infrastructure; gas utilities and infrastructure; and commercial renewables.',35.2251,-80.8494,NULL);
INSERT INTO `companies` VALUES ('DVN','Devon Energy Corp.','Energy','Oil & Gas Exploration & Production','Oklahoma City, Oklahoma','New York Stock Exchange','http://www.devonenergy.com','Devon Energy Corp is engaged in the oil and gas sector. It is an independent energy company involved in the exploration, development and production of oil, natural gas and NGLs.',35.4681,-97.5181,NULL);
INSERT INTO `companies` VALUES ('EA','Electronic Arts','Information Technology','Home Entertainment Software','Redwood City, California','Nasdaq Global Select','http://www.ea.com','Electronic Arts Inc operates in the technology sector. It develops, markets, publishes and distributes video game software and content of various platforms.',37.5233,-122.254,'{\"years\":[2019,2018,2017],\"revenue\":[4950000,5150000,4845000],\"earnings\":[1019000,1043000,967000],\"assets\":[6381000,6004000,5199000],\"liabilities\":[3626000,3989000,3658000]}');
INSERT INTO `companies` VALUES ('EBAY','eBay Inc.','Information Technology','Internet Software & Services','San Jose, California','Nasdaq Global Select','http://www.ebay.com','eBay Inc is a commerce platform and provides online marketplace for sale of goods. Its marketplace platforms include its online marketplace located at www.ebay.com, its localized counterparts and the eBay mobile apps.',37.2958,-121.93,'{\"years\":[2019,2018,2017],\"revenue\":[8636000,8650000,9927000],\"earnings\":[1786000,2530000,-1017000],\"assets\":[18174000,22819000,25986000],\"liabilities\":[15304000,16538000,17937000]}');
INSERT INTO `companies` VALUES ('ECL','Ecolab Inc.','Materials','Specialty Chemicals','St. Paul, Minnesota','New York Stock Exchange','http://www.ecolab.com','Ecolab Inc produces and markets cleaning and sanitation products for the hospitality, healthcare, and industrial markets. It offers a variety of products and services, which include dish and laundry washing systems, pest control, and repair services.',44.9471,-93.0981,NULL);
INSERT INTO `companies` VALUES ('ED','Consolidated Edison','Utilities','Electric Utilities','New York, New York','New York Stock Exchange','https://www.conedison.com','Consolidated Edison Inc functions in the utilities market. It owns energy infrastructure projects and its main business operations are its regulated electric, gas and steam delivery businesses. The CECONY segment generates maximum revenue.',40.7341,-73.9883,NULL);
INSERT INTO `companies` VALUES ('EFX','Equifax Inc.','Industrials','Research & Consulting Services','Atlanta, Georgia','New York Stock Exchange','http://www.equifax.com','Equifax Inc provides information solutions and human resources business process outsourcing services for businesses, governments and consumers. It also provides database management, fraud detection, marketing, business credit, and analytical services.',33.7967,-84.3887,NULL);
INSERT INTO `companies` VALUES ('EIX','Edison Int\'l','Utilities','Electric Utilities','Rosemead, California','New York Stock Exchange','https://www.edison.com','Edison International is engaged in the utilities sector. The company\'s business mainly involves generation and distribution of electric power. It also invests in infrastructure and energy assets, including renewable energy.',34.0539,-118.081,NULL);
INSERT INTO `companies` VALUES ('EMN','Eastman Chemical','Materials','Diversified Chemicals','Kingsport, Tennessee','New York Stock Exchange','http://www.eastman.com','Eastman Chemical Co is a advanced materials and specialty additives company that is engaged in producing and selling a portfolio of chemicals, plastics and fibers.',36.5353,-82.5502,NULL);
INSERT INTO `companies` VALUES ('EMR','Emerson Electric Company','Industrials','Industrial Conglomerates','Ferguson, Missouri','New York Stock Exchange','http://www.emerson.com','Emerson Electric Co is engaged in designing and supplying products and technology, and delivering engineering services and solutions in industrial, commercial and consumer markets.',38.7322,-90.2788,NULL);
INSERT INTO `companies` VALUES ('EQIX','Equinix','Real Estate','REITs','Redwood City, California','Nasdaq Global Select','http://www.equinix.com','Equinix Inc is a network-neutral provider of retail data center, co-location, and interconnection services. Its client base includes network services firms, cloud and IT service providers, financial service firms, digital, and media content providers.',37.5275,-122.261,NULL);
INSERT INTO `companies` VALUES ('ETFC','E*Trade','Financials','Investment Banking & Brokerage','New York, New York','Nasdaq Global Select','https://www.etrade.com','E*TRADE Financial Corp is a financial services company. It provides brokerage and related products and services to individual retail investors. It also provides investor-focused banking products and sweep deposits to retail investors.',40.76,-73.9778,NULL);
INSERT INTO `companies` VALUES ('ETN','Eaton Corporation','Industrials','Industrial Conglomerates','Dublin, Ireland','New York Stock Exchange','http://www.eaton.com','Eaton Corp PLC is a power management company. It provides energy-efficient solutions that help its customers effectively manage electrical, hydraulic and mechanical power. Eaton\'s products include UPS systems, cylinders, circuit breakers, among others.',53.3329,-6.24097,NULL);
INSERT INTO `companies` VALUES ('ETR','Entergy Corp.','Utilities','Electric Utilities','New Orleans, Louisiana','New York Stock Exchange','http://www.entergy.com','Entergy Corp is an energy company. It is engaged in electric power production and retail electric distribution operations in portions of Arkansas, Mississippi, Texas, and Louisiana, including the City of New Orleans.',29.949,-90.0768,NULL);
INSERT INTO `companies` VALUES ('EXC','Exelon Corp.','Utilities','MultiUtilities','Chicago, Illinois','New York Stock Exchange','http://www.exeloncorp.com','Exelon Corp is a power retailer engaged in the utilities sector of United States. The company involves in the power generation and transmission activities. The Generation segment generates maximum revenue for the company.',41.8816,-87.6303,NULL);
INSERT INTO `companies` VALUES ('EXPE','Expedia Inc.','Consumer Discretionary','Internet & Direct Marketing Retail','Bellevue, Washington','New York Stock Exchange','http://www.expediagroup.com','Expedia Group Inc is an online travel company. It offers holiday packages, rental cars, cruises, as well as destination services and activities. The Core OTA segment generates maximum revenue for the company.',47.6283,-122.375,NULL);
INSERT INTO `companies` VALUES ('F','Ford Motor','Consumer Discretionary','Automobile Manufacturers','Dearborn, Michigan','New York Stock Exchange','http://www.ford.com','Ford Motor Co manufactures, markets, and services Ford cars, trucks, sport utility vehicles, electronic vehicles, and Lincoln luxury vehicles. It also provides financial services through Ford Motor Credit Company.',42.3148,-83.2103,'{\"years\":[2019,2018,2017],\"revenue\":[155900000,16033000,156776000],\"earnings\":[47000,3677000,7731000],\"assets\":[258537000,256540000,25849600],\"liabilities\":[225352000,220508000,222820000]}');
INSERT INTO `companies` VALUES ('FB','Facebook','Information Technology','Internet Software & Services','Menlo Park, California','Nasdaq Global Select','http://www.facebook.com','Facebook Inc is the world\'s largest online social network. Its products are Facebook, Instagram, Messenger, WhatsApp, and Oculus. Its products enable people to connect and share through mobile devices and personal computers.',37.481,-122.158,'{\"years\":[2019,2018,2017],\"revenue\":[70697000,55838000,40653000],\"earnings\":[18485000,22112000,15934000],\"assets\":[113376000,97334000,84524000],\"liabilities\":[32322000,13207000,10177000]}');
INSERT INTO `companies` VALUES ('FCX','Freeport-McMoran Cp & Gld','Materials','Copper','Phoenix, Arizona','New York Stock Exchange','http://www.fcx.com','Freeport-McMoRan Inc is a mining company. It operates large, long-lived geographically diverse assets with reserves of copper, gold, and molybdenum. It also has mining operations in the Americas.',33.4517,-112.073,NULL);
INSERT INTO `companies` VALUES ('FDX','FedEx Corporation','Industrials','Air Freight & Logistics','Memphis, Tennessee','New York Stock Exchange','http://www.fedex.com','FedEx Corp is the world\'s largest express courier delivery firm. The company provides courier services through various divisions which include express, ground, office, freight, cross border, trade networks and supply chain.',35.1056,-89.8583,NULL);
INSERT INTO `companies` VALUES ('FE','FirstEnergy Corp','Utilities','Electric Utilities','Akron, Ohio','New York Stock Exchange','http://www.firstenergycorp.com','FirstEnergy Corp is a diversified energy company. It is involved in the generation, transmission and distribution of electricity. It operates in segments such as Regulated Distribution, Regulated Transmission and CES.',41.0834,-81.5183,NULL);
INSERT INTO `companies` VALUES ('FFIV','F5 Networks','Information Technology','Networking Equipment','Seattle, Washington','Nasdaq Global Select','http://www.f5.com','F5 Networks Inc provides software-defined application services designed to ensure that applications delivered over Internet Protocol networks are available to any user, anywhere, anytime, on any device and on any network.',47.6052,-122.331,NULL);
INSERT INTO `companies` VALUES ('FIS','Fidelity National Information Services','Information Technology','Internet Software & Services','Jacksonville, Florida','New York Stock Exchange','http://www.fisglobal.com','Fidelity National Information Services Inc offers a range of solutions in retail and institutional banking, payments, asset and wealth management, risk and compliance, treasury and insurance and provides consulting and outsourcing services.',30.3183,-81.6745,NULL);
INSERT INTO `companies` VALUES ('FITB','Fifth Third Bancorp','Financials','Banks','Cincinnati, Ohio','Nasdaq Global Select','http://www.53.com','Fifth Third Bancorp provides banking products and services. The company offers checking, savings and money market accounts and credit products. Its segments are Commercial Banking, Branch Banking, Consumer Lending and Wealth and Asset Management.',39.1679,-84.4084,NULL);
INSERT INTO `companies` VALUES ('FL','Foot Locker Inc','Consumer Discretionary','Apparel Retail','New York, New York','New York Stock Exchange','http://www.footlocker-inc.com','Foot Locker Inc operates in the footwear industry. Its core business involves retailing of athletic shoes and apparel through mall based stores.',40.7526,-73.9952,NULL);
INSERT INTO `companies` VALUES ('GD','General Dynamics','Industrials','Aerospace & Defense','Falls Church, Virginia','New York Stock Exchange','http://www.generaldynamics.com','General Dynamics Corp is an aerospace and defense company. It offers products and services in business aviation including combat vehicles, weapons systems and munitions, shipbuilding, and communication and information technology services and solutions.',38.9477,-77.3218,NULL);
INSERT INTO `companies` VALUES ('GE','General Electric','Industrials','Industrial Conglomerates','Boston, Massachusetts','New York Stock Exchange','http://www.ge.com','General Electric Co is a digital industrial company. It operates in various segments, including power and water, oil and gas, energy management, aviation, healthcare, transportation, appliances and lighting, and more.',42.3519,-71.048,'{\"years\":[2019,2018,2017],\"revenue\":[95215000,121616000,120468000],\"earnings\":[-4979000,-22355000,-5786000],\"assets\":[266048000,309129000,377945000],\"liabilities\":[236187000,257648000,295959000]}');
INSERT INTO `companies` VALUES ('GIS','General Mills','Consumer Staples','Packaged Foods & Meats','Golden Valley, Minnesota','New York Stock Exchange','http://www.generalmills.com','General Mills Inc is a global manufacturer and marketer of branded consumer foods, such as ready-to-eat breakfast cereals, refrigerated dough and other baking items, snack foods, ice cream, and yogurt',44.9767,-93.3979,NULL);
INSERT INTO `companies` VALUES ('GM','General Motors','Consumer Discretionary','Automobile Manufacturers','Detroit, Michigan','New York Stock Exchange','https://www.gm.com','General Motors Company is an American multinational corporation. It designs, builds and sells cars, trucks and automobile parts. The company also provides automotive financing services through General Motors Financial Company, Inc.',42.3288,-83.039,'{\"years\":[2019,2018,2017],\"revenue\":[137237000,147049000,145588000],\"earnings\":[6732000,8014000,-3864000],\"assets\":[228037000,227339000,212482000],\"liabilities\":[186245000,188479000,177481000]}');
INSERT INTO `companies` VALUES ('GOOG','Alphabet Inc Class C','Information Technology','Internet Software & Services','Mountain View, California','Nasdaq Global Select','https://www.abc.xyz','Alphabet Inc is a provider of internet content products and portals. Its suite of brands includes Search, Android, YouTube, Apps, Maps & Ads.',37.422,-122.084,'{\"years\":[2019,2018,2017],\"revenue\":[161857000,136819000,110855000],\"earnings\":[34343000,30736000,12662000],\"assets\":[275909000,232792000,197295000],\"liabilities\":[74467000,55164000,44793000]}');
INSERT INTO `companies` VALUES ('GPS','Gap (The)','Consumer Discretionary','Apparel Retail','San Francisco, California','New York Stock Exchange','http://www.gapinc.com','Gap Inc is a global apparel and accessories retailer. The company offers products for men, women, and children under various brands such as Gap, Banana Republic, Old Navy, Athleta, and Intermix.',37.7855,-122.397,NULL);
INSERT INTO `companies` VALUES ('GRMN','Garmin Ltd.','Consumer Discretionary','Consumer Electronics','Schaffhausen, Switzerland','Nasdaq Global Select','http://www.garmin.com','Garmin Ltd designs, develops, manufactures, markets and distributes hand-held, wrist-based, portable, fixed-mount, positioning system enabled and other navigation, communication and sensor-based products.',47.6996,8.63285,NULL);
INSERT INTO `companies` VALUES ('GS','Goldman Sachs Group','Financials','Investment Banking & Brokerage','New York, New York','New York Stock Exchange','http://www.gs.com','Goldman Sachs Group Inc is engaged in capital market activities. Its services primarily include investment banking operations.',40.7148,-74.0144,NULL);
INSERT INTO `companies` VALUES ('GT','Goodyear Tire & Rubber','Consumer Discretionary','Tires & Rubber','Akron, Ohio','Nasdaq Global Select','http://www.goodyear.com','Goodyear Tire & Rubber Co is engaged in manufacturing of tires for various applications. The company\'s products are used in automobiles, trucks, buses, and others. It also manufactures and markets rubber-related chemicals for various applications.',41.0577,-81.4769,NULL);
INSERT INTO `companies` VALUES ('HAL','Halliburton Co.','Energy','Oil & Gas Equipment & Services','Houston, Texas','New York Stock Exchange','http://www.halliburton.com','Halliburton Co is a provider of services and products to the upstream oil and natural gas industry throughout the lifecycle of the reservoir, from locating hydrocarbons and managing geological data, to drilling and formation evaluation.',29.9468,-95.3258,NULL);
INSERT INTO `companies` VALUES ('HD','Home Depot','Consumer Discretionary','Home Improvement Retail','Atlanta, Georgia','New York Stock Exchange','http://www.homedepot.com','The Home Depot Inc is a home improvement specialty retailer. Its stores sell an assortment of building materials, home improvement and lawn and garden products and provide a number of services.',33.8655,-84.4814,NULL);
INSERT INTO `companies` VALUES ('HES','Hess Corporation','Energy','Integrated Oil & Gas','New York, New York','New York Stock Exchange','http://www.hess.com','Hess Corp is an oil and gas company involved in the exploration, development, production, transportation, purchase and sale of crude oil, natural gas liquids, and natural gas with production operations.',40.7578,-73.9824,NULL);
INSERT INTO `companies` VALUES ('HOG','Harley-Davidson','Consumer Discretionary','Motorcycle Manufacturers','Milwaukee, Wisconsin','New York Stock Exchange','http://www.harley-davidson.com','Harley-Davidson Inc produces and sells heavyweight motorcycles, as well as offers motorcycle parts, accessories, and related services. It operates in two segments, Motorcycles and Related Products, and Financial Services.',43.0461,-87.96,'{\"years\":[2019,2018,2017],\"revenue\":[5361789,5716875,5647224],\"earnings\":[423635,531451,521759],\"assets\":[10528159,10665664,9972672],\"liabilities\":[8724160,8891715,8128395]}');
INSERT INTO `companies` VALUES ('HPE','Hewlett Packard Enterprise','Information Technology','Technology Hardware, Storage & Peripherals','Palo Alto, California','New York Stock Exchange','https://www.hpe.com','Hewlett Packard Enterprise Co is a communication equipment company that provides servers, storage, networking and technology services. Its business segments are Enterprise Group, Software, Enterprise Services, Financial Services and Corporate Investments.',37.4199,-121.979,NULL);
INSERT INTO `companies` VALUES ('HPQ','HP Inc.','Information Technology','Computer Hardware','Palo Alto, California','New York Stock Exchange','http://www.hp.com','Hewlett-Packard Company is a provider of products, technologies, software, solutions & services to individual consumers, small- and medium-sized businesses and large enterprises, including customers in the government, health and education sectors.',37.4122,-122.149,NULL);
INSERT INTO `companies` VALUES ('HSY','The Hershey Company','Consumer Staples','Packaged Foods & Meats','Hershey, Pennsylvania','New York Stock Exchange','http://www.thehersheycompany.com','The Hershey Co operates as a confectionery manufacturer in the United States engaged in the chocolate industry. The firm has more than 80 brands, including Hershey\'s, Reese\'s, Kit Kat, Twizzlers, and Ice Breakers with a business presence across the world.',40.2869,-76.6488,NULL);
INSERT INTO `companies` VALUES ('IBM','International Business Machines','Information Technology','IT Consulting & Other Services','Armonk, New York','New York Stock Exchange','http://www.ibm.com','International Business Machines Corp offers a variety of IT services along with software, and hardware. It has operations in over 170 countries and provides planning, build, manage, and maintain IT infrastructure, platforms, applications, and services.',41.1083,-73.7205,'{\"years\":[2019,2018,2017],\"revenue\":[77147000,79590000,79139000],\"earnings\":[9431000,8728000,5753000],\"assets\":[152186000,123382000,125356000],\"liabilities\":[131201000,106452000,107631000]}');
INSERT INTO `companies` VALUES ('INTC','Intel Corp.','Information Technology','Semiconductors','Santa Clara, California','Nasdaq Global Select','https://www.intel.in','Intel Corp is the world\'s largest chipmaker. It engaged in making a semiconductor chip. It designs and manufactures integrated digital technology products like integrated circuits, for industries such as computing and communications.',37.3873,-121.964,'{\"years\":[2019,2018,2017],\"revenue\":[71965000,70848000,62761000],\"earnings\":[21048000,21053000,9601000],\"assets\":[31239000,28787000,29500000],\"liabilities\":[58865000,52981000,53364000]}');
INSERT INTO `companies` VALUES ('INTU','Intuit Inc.','Information Technology','Internet Software & Services','Mountain View, California','Nasdaq Global Select','http://www.intuit.com','Intuit Inc creates business and financial management solutions for small businesses, consumers, and accounting professionals. The company\'s products and services include QuickBooks and TurboTax.',37.4314,-122.098,NULL);
INSERT INTO `companies` VALUES ('IP','International Paper','Materials','Paper Packaging','Memphis, Tennessee','New York Stock Exchange','http://www.internationalpaper.com','International Paper Co produces and distributes printing paper, packaging, forest products, and chemical products. The company operates in three segments namely; Industrial Packaging, Printing Papers, and Global Cellulose Fibers.',35.0623,-89.7877,NULL);
INSERT INTO `companies` VALUES ('IQV','IQVIA Holdings Inc.','Health Care','Life Sciences Tools & Service','Durham, North Carolina','New York Stock Exchange','https://www.quintilesims.com','IQVIA Holdings Inc is an information and technology-enabled healthcare service provider to the pharmaceutical services, biotechnology, and healthcare industries. The Commercial Solutions and Research and Development Solutions generate maximum revenue.',35.8808,-78.8407,NULL);
INSERT INTO `companies` VALUES ('IT','Gartner Inc','Information Technology','IT Consulting & Other Services','Stamford, Connecticut','New York Stock Exchange','http://www.gartner.com','Gartner Inc is an information technology research and advisory company. It offers services to business leaders in high-tech and telecom enterprises and professional services firms, to supply chain professionals and technology investors.',41.0305,-73.5503,NULL);
INSERT INTO `companies` VALUES ('JCI','Johnson Controls International','Industrials','Building Products','Cork, Ireland','New York Stock Exchange','http://www.johnsoncontrols.com','Johnson Controls International plc operates as a diversified technology and multi industrial company worldwide. ',51.8976,-8.4637,NULL);
INSERT INTO `companies` VALUES ('JNJ','Johnson & Johnson','Health Care','Health Care Equipment','New Brunswick, New Jersey','New York Stock Exchange','http://www.jnj.com','Johnson & Johnson researches and develops, manufactures, and sells various products in the health care field worldwide. ',40.4979,-74.443,NULL);
INSERT INTO `companies` VALUES ('JNPR','Juniper Networks','Information Technology','Networking Equipment','Sunnyvale, California','New York Stock Exchange','http://www.juniper.net','Juniper Networks Inc operates in the communication equipment industry. It designs, develops and sells products and services that provide customers with network infrastructure. It caters to communication service providers and companies.',37.4075,-122.029,NULL);
INSERT INTO `companies` VALUES ('JPM','JPMorgan Chase & Co.','Financials','Banks','New York, New York','New York Stock Exchange','http://www.jpmorganchase.com','JPMorgan Chase & Co. operates as a financial services company worldwide.',40.7558,-73.9756,'{\"years\":[2019,2018,2017],\"revenue\":[115627000,109029000,99624000],\"earnings\":[36431000,32474000,24441000],\"assets\":[2687379000,2622532000,2533600000],\"liabilities\":[2426049000,2366017000,2277907000]}');
INSERT INTO `companies` VALUES ('K','Kellogg Co.','Consumer Staples','Packaged Foods & Meats','Battle Creek, Michigan','New York Stock Exchange','http://www.kelloggcompany.com','Kellogg Company, together with its subsidiaries, manufactures and markets ready-to-eat cereal and convenience foods. ',42.3209,-85.1861,'{\"years\":[2019,2018,2017],\"revenue\":[13578000,13547000,12854000],\"earnings\":[960000,1336000,1254000],\"assets\":[17564000,17780000,16351000],\"liabilities\":[14817000,15179000,14173000]}');
INSERT INTO `companies` VALUES ('KHC','Kraft Heinz Co','Consumer Staples','Packaged Foods & Meats','Pittsburgh, Pennsylvania','New York Stock Exchange','http://www.kraftheinzcompany.com','The Kraft Heinz Company, together with its subsidiaries, manufactures and markets food and beverage products in the United States, Canada, the United Kingdom, and internationally.',40.4407,-79.9964,'{\"years\":[2019,2018,2017],\"revenue\":[24977000,26268000,26232000],\"earnings\":[1935000,-10192000,10999000],\"assets\":[101450000,103461000,120232000],\"liabilities\":[49701000,51686000,53991000]}');
INSERT INTO `companies` VALUES ('KMB','Kimberly-Clark','Consumer Staples','Household Products','Irving, Texas','New York Stock Exchange','http://www.kimberly-clark.com','Kimberly-Clark Corporation, together with its subsidiaries, manufactures and markets personal care and consumer tissue products worldwide.',32.87,-96.9506,NULL);
INSERT INTO `companies` VALUES ('KMX','Carmax Inc','Consumer Discretionary','Specialty Stores','Richmond, Virginia','New York Stock Exchange','http://www.carmax.com','CarMax, Inc., through its subsidiaries, operates as a retailer of used vehicles in the United States. The company operates in two segments, CarMax Sales Operations and CarMax Auto Finance. ',37.6394,-77.6713,NULL);
INSERT INTO `companies` VALUES ('L','Loews Corp.','Financials','Multi-Sector Holdings','New York, New York','New York Stock Exchange','http://www.loews.com','Loews Corporation provides commercial property and casualty insurance in the United States and internationally. ',40.7645,-73.9702,NULL);
INSERT INTO `companies` VALUES ('LMT','Lockheed Martin Corp.','Industrials','Aerospace & Defense','Bethesda, Maryland','New York Stock Exchange','http://www.lockheedmartin.com','Lockheed Martin Corporation, a security and aerospace company, engages in the research, design, development, manufacture, integration, and sustainment of technology systems, products, and services worldwide.',39.0311,-77.1389,NULL);
INSERT INTO `companies` VALUES ('LNC','Lincoln National','Financials','Multi-line Insurance','Radnor, Pennsylvania','New York Stock Exchange','http://www.lfg.com','Lincoln National Corporation, through its subsidiaries, operates multiple insurance and retirement businesses in the United States. ',40.043,-75.3656,NULL);
INSERT INTO `companies` VALUES ('LOW','Lowe\'s Cos.','Consumer Discretionary','Home Improvement Retail','Mooresville, North Carolina','New York Stock Exchange','http://www.lowes.com','Lowe\'s Companies, Inc., together with its subsidiaries, operates as a home improvement retailer in the United States, Canada, and Mexico. ',35.5417,-80.8541,NULL);
INSERT INTO `companies` VALUES ('MA','Mastercard Inc.','Information Technology','Internet Software & Services','Harrison, New York','New York Stock Exchange','http://www.mastercard.com','Mastercard Inc is a technology company in the payments industry. The Company connects consumers, financial institutions, merchants, governments and businesses, enabling them to use electronic forms of payment instead of cash and checks.',41.0235,-73.7143,'{\"years\":[2019,2018,2017],\"revenue\":[16883000,14950000,12497000],\"earnings\":[8118000,5859000,3915000],\"assets\":[29236000,24860000,21329000],\"liabilities\":[23319000,19442000,15832000]}');
INSERT INTO `companies` VALUES ('MAR','Marriott Int\'l.','Consumer Discretionary','Hotels, Resorts & Cruise Lines','Bethesda, Maryland','Nasdaq Global Select','http://www.marriott.com','Marriott International, Inc. operates, franchises, and licenses hotel, residential, and timeshare properties worldwide. ',39.0247,-77.138,'{\"years\":[2019,2018,2017],\"revenue\":[20972000,20758000,22894000],\"earnings\":[1273000,1907000,1372000],\"assets\":[25051000,23696000,23948000],\"liabilities\":[24348000,21471000,20217000]}');
INSERT INTO `companies` VALUES ('MAT','Mattel Inc.','Consumer Discretionary','Leisure Products','El Segundo, California','Nasdaq Global Select','http://www.corporate.mattel.com','Mattel, Inc., a children\'s entertainment company, designs and produces toys and consumer products worldwide.',33.925,-118.391,NULL);
INSERT INTO `companies` VALUES ('MCD','McDonald\'s Corp.','Consumer Discretionary','Restaurants','Oak Brook, Illinois','New York Stock Exchange','http://www.aboutmcdonalds.com','McDonald\'s Corporation operates and franchises McDonald\'s restaurants in the United States and internationally. Its restaurants offer various food products and beverages, as well as breakfast menu. As of December 31, 2019, the company operated 38,695 restaurants. McDonald\'s Corporation was founded in 1940 and is based in Chicago, Illinois.',41.8349,-87.9446,'{\"years\":[2019,2018,2017],\"revenue\":[21076500,21025200,22820400],\"earnings\":[6025400,5924300,5192300],\"assets\":[3557900,4053200,5327200],\"liabilities\":[55721100,39069600,37071700]}');
INSERT INTO `companies` VALUES ('MET','MetLife Inc.','Financials','Life & Health Insurance','New York, New York','New York Stock Exchange','http://www.metlife.com','MetLife, Inc. engages in the insurance, annuities, employee benefits, and asset management businesses worldwide. ',40.7537,-73.9765,NULL);
INSERT INTO `companies` VALUES ('MMM','3M Company','Industrials','Industrial Conglomerates','St. Paul, Minnesota','New York Stock Exchange','http://www.3m.com','3M Company develops, manufactures, and markets various products worldwide. ',44.9511,-92.9964,'{\"years\":[2019,2018,2017],\"revenue\":[32136000,32765000,31657000],\"earnings\":[4570000,5349000,4858000],\"assets\":[44659000,36500000,37987000],\"liabilities\":[34533000,26652000,26365000]}');
INSERT INTO `companies` VALUES ('MO','Altria Group Inc','Consumer Staples','Tobacco','Richmond, Virginia','New York Stock Exchange','http://www.altria.com','Altria Group, Inc., through its subsidiaries, manufactures and sells cigarettes, smokeless products, and wine in the United States.',37.6024,-77.5179,NULL);
INSERT INTO `companies` VALUES ('MS','Morgan Stanley','Financials','Investment Banking & Brokerage','New York, New York','New York Stock Exchange','http://www.morganstanley.com','Morgan Stanley, a financial holding company, provides various financial products and services to corporations, governments, financial institutions, and individuals in the Americas, Europe, the Middle East, Africa, and Asia. ',40.7598,-73.9856,NULL);
INSERT INTO `companies` VALUES ('MSFT','Microsoft Corp.','Information Technology','Systems Software','Redmond, Washington','Nasdaq Global Select','http://www.microsoft.com','Microsoft Corp is a technology company. It develop, license, and support a wide range of software products and services. Its business is organized into three segments: Productivity and Business Processes, Intelligent Cloud, and More Personal Computing.',47.6423,-122.137,'{\"years\":[2019,2018,2017],\"revenue\":[125843000,110360000,89950000],\"earnings\":[39240000,16571000,21204000],\"assets\":[286556000,258848000,241086000],\"liabilities\":[184226000,176130000,168692000]}');
INSERT INTO `companies` VALUES ('MU','Micron Technology','Information Technology','Semiconductors','Boise, Idaho','Nasdaq Global Select','http://www.micron.com','Micron Technology Inc along with its subsidiaries provide memory and storage solutions. Its product portfolio consists of memory and storage technologies such as DRAM, NAND, NOR and 3D XPoint memory.',43.5309,-116.149,NULL);
INSERT INTO `companies` VALUES ('NDAQ','NASDAQ OMX Group','Financials','Diversified Financial Services','New York, New York','Nasdaq Global Select','http://www.nasdaq.com','Nasdaq, Inc. operates as a technology company that serves capital markets and other industries worldwide.',40.7557,-73.9856,NULL);
INSERT INTO `companies` VALUES ('NFLX','Netflix Inc.','Information Technology','Internet Software & Services','Los Gatos, California','Nasdaq Global Select','http://www.netflix.com','Netflix Inc provides multimedia content through the internet. It provides a subscription based platform for television shows, movies and original series.',37.2596,-121.963,'{\"years\":[2019,2018,2017],\"revenue\":[20156447,15794341,11692713],\"earnings\":[1866916,1211242,558929],\"assets\":[33975712,25974400,19012742],\"liabilities\":[26393555,20735635,15430786]}');
INSERT INTO `companies` VALUES ('NKE','Nike','Consumer Discretionary','Apparel, Accessories & Luxury Goods','Washington County, Oregon','New York Stock Exchange','http://www.nike.com','NIKE, Inc., together with its subsidiaries, designs, develops, markets, and sells athletic footwear, apparel, equipment, and accessories worldwide.',45.5078,-122.828,'{\"years\":[2019,2018,2017],\"revenue\":[39117000,36397000,34350000],\"earnings\":[4029000,1933000,4240000],\"assets\":[23717000,22536000,23259000],\"liabilities\":[14677000,12724000,10852000]}');
INSERT INTO `companies` VALUES ('NSC','Norfolk Southern Corp.','Industrials','Railroads','Norfolk, Virginia','New York Stock Exchange','http://www.nscorp.com','Norfolk Southern Corporation, together with its subsidiaries, engages in the rail transportation of raw materials, intermediate products, and finished goods in the United States. ',36.8455,-76.2881,NULL);
INSERT INTO `companies` VALUES ('NTAP','NetApp','Information Technology','Internet Software & Services','Sunnyvale, California','Nasdaq Global Select','http://www.netapp.com','NetApp Inc provides technology solutions. It is engaged in the design, manufacturing, marketing, and technical support of high-performance storage and data management solutions. Its core product offering include data storage devices such as flash drives.',37.415,-122.01,NULL);
INSERT INTO `companies` VALUES ('NVDA','Nvidia Corporation','Information Technology','Semiconductors','Santa Clara, California','Nasdaq Global Select','http://www.nvidia.com','NVIDIA Corp is a developer of graphics processing unit. It caters to areas like gaming, professional visualization, datacenter and automobiles.',37.3706,-121.967,NULL);
INSERT INTO `companies` VALUES ('NWL','Newell Brands','Consumer Discretionary','Housewares & Specialties','Sandy Springs, Georgia','Nasdaq Global Select','ttp://www.newellbrands.com','Newell Brands Inc. designs, manufactures, sources, and distributes consumer and commercial products worldwide. ',33.9372,-84.3529,NULL);
INSERT INTO `companies` VALUES ('ORCL','Oracle Corp.','Information Technology','Application Software','Redwood Shores, California','New York Stock Exchange','http://www.oracle.com','Oracle Corp is a computer software company. It sells enterprise information technology solutions, including databases, middleware, applications, and hardware. The Company primarily offers software licenses, support, and maintenance services worldwide.',37.5272,-122.261,'{\"years\":[2019,2018,2017],\"revenue\":[39068000,39506000,39831000],\"earnings\":[10135000,11083000,3825000],\"assets\":[108709000,137264000,134991000],\"liabilities\":[86346000,91040000,80745000]}');
INSERT INTO `companies` VALUES ('ORLY','O\'Reilly Automotive','Consumer Discretionary','Specialty Stores','Springfield, Missouri','Nasdaq Global Select','http://www.oreillyauto.com','O\'Reilly Automotive, Inc., together with its subsidiaries, engages in the retail of automotive aftermarket parts, tools, supplies, equipment, and accessories in the United States. ',37.2076,-93.249,NULL);
INSERT INTO `companies` VALUES ('PEP','PepsiCo Inc.','Consumer Staples','Soft Drinks','Purchase, New York','Nasdaq Global Select','http://www.pepsico.com','PepsiCo, Inc. operates as a food and beverage company worldwide.',41.0344,-73.6929,'{\"years\":[2019,2018,2017],\"revenue\":[67161000,64661000,63525000],\"earnings\":[7314000,12515000,4857000],\"assets\":[78547000,77648000,79804000],\"liabilities\":[63679000,63046000,68823000]}');
INSERT INTO `companies` VALUES ('PFE','Pfizer Inc.','Health Care','Pharmaceuticals','New York, New York','New York Stock Exchange','http://www.pfizer.com','Pfizer Inc. develops, manufactures, and sells healthcare products worldwide.',40.7503,-73.9724,NULL);
INSERT INTO `companies` VALUES ('PG','Procter & Gamble','Consumer Staples','Personal Products','Cincinnati, Ohio','New York Stock Exchange','http://www.pginvestor.com','The Procter & Gamble Company provides branded consumer packaged goods to consumers in North and Latin America, Europe, the Asia Pacific, Greater China, India, the Middle East, and Africa.',39.1032,-84.5052,NULL);
INSERT INTO `companies` VALUES ('PGR','Progressive Corp.','Financials','Property & Casualty Insurance','Mayfield Village, Ohio','New York Stock Exchange','http://www.progressive.com','The Progressive Corporation, through its subsidiaries, provides personal and commercial auto insurance, residential property insurance, and other specialty property-casualty insurance and related services primarily in the United States.',41.5346,-81.4509,NULL);
INSERT INTO `companies` VALUES ('PKI','PerkinElmer','Health Care','Health Care Equipment','Waltham, Massachusetts','New York Stock Exchange','http://www.perkinelmer.com','PerkinElmer, Inc. provides products, services, and solutions to the diagnostics, life sciences, and applied services markets worldwide.',42.4048,-71.2743,NULL);
INSERT INTO `companies` VALUES ('PM','Philip Morris International','Consumer Staples','Tobacco','New York, New York','New York Stock Exchange','http://www.pmi.com','Philip Morris International Inc., through its subsidiaries, manufactures and sells cigarettes, other nicotine-containing products, smoke-free products, and related electronic devices and accessories.',40.7519,-73.9783,NULL);
INSERT INTO `companies` VALUES ('PPL','PPL Corp.','Utilities','Electric Utilities','Allentown, Pennsylvania','New York Stock Exchange','http://www.pplweb.com','PPL Corporation, a utility holding company, delivers electricity and natural gas in the United States and the United Kingdom. ',40.6108,-75.4799,NULL);
INSERT INTO `companies` VALUES ('PSX','Phillips 66','Energy','Oil & Gas Refining & Marketing & Transportation','Houston, Texas','New York Stock Exchange','http://www.phillips66.com','Phillips 66 operates as an energy manufacturing and logistics company. ',29.741,-95.5608,NULL);
INSERT INTO `companies` VALUES ('PYPL','PayPal','Information Technology','Data Processing & Outsourced Services','San Jose, California','Nasdaq Global Select','https://www.paypal.com','PayPal Holdings Inc is a technology platform company that enables digital and mobile payments on behalf of consumers and merchants. The company\'s payments platform includes PayPal, PayPal Credit, Venmo, Xoom and Braintree products.',37.3764,-121.923,'{\"years\":[2019,2018,2017],\"revenue\":[17772000,15451000,13094000],\"earnings\":[2459000,2057000,1795000],\"assets\":[51333000,43332000,40774000],\"liabilities\":[34404000,27946000,24780000]}');
INSERT INTO `companies` VALUES ('QCOM','QUALCOMM Inc.','Information Technology','Semiconductors','San Diego, California','Nasdaq Global Select','http://www.qualcomm.com','Qualcomm Inc develops and licenses wireless technology. It also engages in designing chips for mobile phones. The company is also the world\'s largest wireless chip vendor, supplying many premier handset makers with leading-edge processors.',32.8972,-117.219,NULL);
INSERT INTO `companies` VALUES ('RHT','Red Hat Inc.','Information Technology','Systems Software','Raleigh, North Carolina','New York Stock Exchange','http://www.redhat.com','Red Hat Inc is a software company operating business across the world. It is primarily engaged in providing services to its version of the open-source Linux software operating systems, middleware, storage, virtualization, and management tools.',35.7753,-78.638,NULL);
INSERT INTO `companies` VALUES ('ROK','Rockwell Automation Inc.','Industrials','Industrial Conglomerates','Milwaukee, Wisconsin','New York Stock Exchange','http://www.rockwellautomation.com','Rockwell Automation, Inc. provides industrial automation and digital transformation solutions. ',43.0182,-87.9122,NULL);
INSERT INTO `companies` VALUES ('SBUX','Starbucks Corp.','Consumer Discretionary','Restaurants','Seattle, Washington','Nasdaq Global Select','http://www.starbucks.com','Starbucks Corporation, together with its subsidiaries, operates as a roaster, marketer, and retailer of specialty coffee worldwide.',47.5809,-122.336,NULL);
INSERT INTO `companies` VALUES ('SHW','Sherwin-Williams','Materials','Specialty Chemicals','Cleveland, Ohio','New York Stock Exchange','http://www.sherwin.com','The Sherwin-Williams Company develops, manufactures, distributes, and sells paints, coatings, and related products to professional, industrial, commercial, and retail customers. ',41.4972,-81.6926,NULL);
INSERT INTO `companies` VALUES ('SLB','Schlumberger Ltd.','Energy','Oil & Gas Equipment & Services','Houston, Texas','New York Stock Exchange','http://www.slb.com','Schlumberger Limited supplies technology for reservoir characterization, drilling, production, and processing to the oil and gas industry worldwide. ',29.7495,-95.4734,NULL);
INSERT INTO `companies` VALUES ('SNA','Snap-On Inc.','Consumer Discretionary','Household Appliances','Kenosha, Wisconsin','New York Stock Exchange','http://www.snapon.com','Snap-on Incorporated manufactures and markets tools, equipment, diagnostics, and repair information and systems solutions for professional users worldwide. ',42.5567,-87.8436,NULL);
INSERT INTO `companies` VALUES ('SO','Southern Co.','Utilities','Electric Utilities','Atlanta, Georgia','New York Stock Exchange','http://www.southerncompany.com','The Southern Company, through its subsidiaries, engages in the generation, transmission, and distribution of electricity.',33.7643,-84.3883,NULL);
INSERT INTO `companies` VALUES ('STI','SunTrust Banks','Financials','Banks','Atlanta, Georgia','New York Stock Exchange','http://www.suntrust.com',NULL,NULL,NULL,NULL);
INSERT INTO `companies` VALUES ('STT','State Street Corp.','Financials','Diversified Financial Services','Boston, Massachusetts','New York Stock Exchange','http://www.statestreet.com','State Street Corporation, through its subsidiaries, provides a range of financial products and services to institutional investors worldwide',42.3526,-71.0583,NULL);
INSERT INTO `companies` VALUES ('STX','Seagate Technology','Information Technology','Computer Storage & Peripherals','Dublin, Ireland','Nasdaq Global Select','http://www.seagate.com','Seagate Technology PLC is a producer of hard disk drives (HDD) globally. It designs, develops, and manufactures a broad range of HDDs used in desktop PC, notebook PC, game consoles, digital video recorders, and enterprise storage markets.',53.3423,-6.227,'{\"years\":[2019,2018,2017],\"revenue\":[10509000,10390000,11184000],\"earnings\":[1004000,2012000,1182000],\"assets\":[8885000,9410000,9268000],\"liabilities\":[6723000,7745000,7904000]}');
INSERT INTO `companies` VALUES ('SYMC','Symantec Corp.','Information Technology','Application Software','Mountain View, California','Nasdaq Global Select','http://www.symantec.com','Symantec Corp provides software solutions attending to security and backup. Its products and services protect data across mobile devices, enterprise data centers and cloud-based systems.',NULL,NULL,NULL);
INSERT INTO `companies` VALUES ('SYY','Sysco Corp.','Consumer Staples','Food Distributors','Houston, Texas','New York Stock Exchange','http://www.sysco.com','Sysco Corporation, through its subsidiaries, markets and distributes a range of food and related products primarily to the foodservice or food-away-from-home industry in the United States, Canada, the United Kingdom, France, and internationally',29.7588,-95.6202,NULL);
INSERT INTO `companies` VALUES ('T','AT&T Inc','Telecommunications Services','Integrated Telecommunications Services','Dallas, Texas','New York Stock Exchange','http://www.att.com','AT&T Inc. provides telecommunication, media, and technology services worldwide.',32.7796,-96.7988,NULL);
INSERT INTO `companies` VALUES ('TAP','Molson Coors Brewing Company','Consumer Staples','Brewers','Denver, Colorado','New York Stock Exchange','http://www.molsoncoors.com','Molson Coors Beverage Company manufactures, markets, and sells beer and other malt beverage products in the United States, Canada, Europe, and internationally. ',39.7478,-104.99,NULL);
INSERT INTO `companies` VALUES ('TGT','Target Corp.','Consumer Discretionary','General Merchandise Stores','Minneapolis, Minnesota','New York Stock Exchange','http://www.targetcorp.com','Target Corporation operates as a general merchandise retailer in the United States. ',44.9738,-93.2757,NULL);
INSERT INTO `companies` VALUES ('TIF','Tiffany & Co.','Consumer Discretionary','Apparel, Accessories & Luxury Goods','New York, New York','New York Stock Exchange','http://www.tiffany.com',NULL,NULL,NULL,NULL);
INSERT INTO `companies` VALUES ('TPR','Tapestry Inc','Consumer Discretionary','Apparel, Accessories & Luxury Goods','New York, New York','New York Stock Exchange','http://www.tapestry.com','Tapestry, Inc. provides luxury accessories and branded lifestyle products in the United States, Japan, Greater China, Other Asia, and internationally.',40.7531,-74.0012,NULL);
INSERT INTO `companies` VALUES ('TRIP','TripAdvisor','Consumer Discretionary','Internet & Direct Marketing Retail','Newton, Massachusetts','Nasdaq Global Select','http://www.tripadvisor.com','TripAdvisor, Inc. operates as an online travel company.',42.2978,-71.2194,'{\"years\":[2019,2018,2017],\"revenue\":[1560000,1615000,1556000],\"earnings\":[126000,113000,-19000],\"assets\":[1984000,2167000,2272000],\"liabilities\":[823000,696000,909000]}');
INSERT INTO `companies` VALUES ('TXN','Texas Instruments','Information Technology','Semiconductors','Dallas, Texas','Nasdaq Global Select','http://www.ti.com','Texas Instruments Inc designs and makes semiconductors that it sells to electronics designers and manufacturers. It also manufactures digital signal processors used in wireless communications, and microcontrollers used in various electronics applications.',32.911,-96.7523,NULL);
INSERT INTO `companies` VALUES ('UA','Under Armour','Consumer Discretionary','Apparel, Accessories & Luxury Goods','Baltimore, Maryland','New York Stock Exchange','http://www.underarmour.com','Under Armour, Inc., together with its subsidiaries, develops, markets, and distributes branded performance apparel, footwear, and accessories for men, women, and youth primarily in North America, Europe, the Middle East, Africa, the Asia-Pacific, and Latin America.',39.2751,-76.5913,NULL);
INSERT INTO `companies` VALUES ('UNP','Union Pacific','Industrials','Railroads','Omaha, Nebraska','New York Stock Exchange','http://www.up.com','Union Pacific Corporation, through its subsidiary, Union Pacific Railroad Company, engages in the railroad business in the United States.',41.2591,-95.9351,NULL);
INSERT INTO `companies` VALUES ('USB','U.S. Bancorp','Financials','Banks','Minneapolis, Minnesota','New York Stock Exchange','https://www.usbank.com','U.S. Bancorp, a financial services holding company, provides various financial services in the United States.',44.9756,-93.274,NULL);
INSERT INTO `companies` VALUES ('UTX','United Technologies','Industrials','Industrial Conglomerates','Hartford, Connecticut','New York Stock Exchange','http://www.utc.com',NULL,NULL,NULL,NULL);
INSERT INTO `companies` VALUES ('V','Visa Inc.','Information Technology','Internet Software & Services','San Francisco, California','New York Stock Exchange','http://www.corporate.visa.com','Visa Inc is a payments technology company working to enable consumers, businesses, banks and governments to use fast, secure and reliable digital currency. The Company operates processing networks - VisaNet.',37.6228,-122.395,NULL);
INSERT INTO `companies` VALUES ('VIAB','Viacom Inc.','Consumer Discretionary','Broadcasting & Cable TV','New York, New York','Nasdaq Global Select','http://www.viacom.com',NULL,NULL,NULL,NULL);
INSERT INTO `companies` VALUES ('VZ','Verizon Communications','Telecommunications Services','Integrated Telecommunications Services','New York, New York','New York Stock Exchange','http://www.verizon.com','Verizon Communications Inc. offers communications, information, and entertainment products and services to consumers, businesses, and governmental entities worldwide. ',40.7547,-73.9849,NULL);
INSERT INTO `companies` VALUES ('WBA','Walgreens Boots Alliance','Consumer Staples','Drug Retail','Deerfield, Illinois','Nasdaq Global Select','http://www.walgreens.com','Walgreens Boots Alliance, Inc. operates as a pharmacy-led health and beauty retail company.',42.1555,-87.8686,NULL);
INSERT INTO `companies` VALUES ('WDC','Western Digital','Information Technology','Computer Storage & Peripherals','Irvine, California','Nasdaq Global Select','https://www.wdc.com','Western Digital Corp is the global leader in the hard disk drive market. It develops, manufactures, and provides data storage solutions that enable consumers to create, manage, experience and preserve digital content. Its products include HDDs and SSDs.',33.673,-117.841,'{\"years\":[2019,2018,2017],\"revenue\":[16569000,20647000,19093000],\"earnings\":[-754000,675000,397000],\"assets\":[26370000,29235000,29860000],\"liabilities\":[16403000,17704000,18442000]}');
INSERT INTO `companies` VALUES ('WFC','Wells Fargo','Financials','Banks','San Francisco, California','New York Stock Exchange','http://www.wellsfargo.com','Wells Fargo & Company, a diversified financial services company, provides banking, investment, mortgage, and consumer and commercial finance products and services to individuals, businesses, and institutions in the United States and internationally.',37.7934,-122.403,NULL);
INSERT INTO `companies` VALUES ('WHR','Whirlpool Corp.','Consumer Discretionary','Household Appliances','Benton Harbor, Michigan','New York Stock Exchange','http://www.whirlpoolcorp.com','Whirlpool Corporation manufactures and markets home appliances and related products. ',42.15,-86.443,NULL);
INSERT INTO `companies` VALUES ('WM','Waste Management Inc.','Industrials','Environmental Services','Houston, Texas','New York Stock Exchange','http://www.wm.com','Waste Management, Inc., through its subsidiaries, provides waste management environmental services to residential, commercial, industrial, and municipal customers in North America. ',29.7557,-95.3639,NULL);
INSERT INTO `companies` VALUES ('WMB','Williams Cos.','Energy','Oil & Gas Exploration & Production','Tulsa, Oklahoma','New York Stock Exchange','http://www.williams.com','The Williams Companies, Inc., together with its subsidiaries, operates as an energy infrastructure company primarily in the United States. ',36.1553,-95.9906,NULL);
INSERT INTO `companies` VALUES ('WMT','Wal-Mart Stores','Consumer Staples','Hypermarkets & Super Centers','Bentonville, Arkansas','New York Stock Exchange','http://www.walmart.com','Walmart Inc. engages in the retail and wholesale operations in various formats worldwide. ',36.3652,-94.2175,'{\"years\":[2019,2018,2017],\"revenue\":[523964000,514405000,500343000],\"earnings\":[14881000,6670000,9862000],\"assets\":[236495000,219295000,204522000],\"liabilities\":[154943000,139661000,123700000]}');
INSERT INTO `companies` VALUES ('WY','Weyerhaeuser Corp.','Real Estate','REITs','Federal Way, Washington','New York Stock Exchange','http://www.weyerhaeuser.com','Weyerhaeuser Company, one of the world\'s largest private owners of timberlands, began operations in 1900.',47.6004,-122.332,NULL);
INSERT INTO `companies` VALUES ('WYNN','Wynn Resorts Ltd','Consumer Discretionary','Casinos & Gaming','Las Vegas, Nevada','New York Stock Exchange','https://www.wynnresorts.com','Wynn Resorts, Limited designs, develops, and operates integrated resorts. ',36.1271,-115.165,NULL);
INSERT INTO `companies` VALUES ('XEL','Xcel Energy Inc','Utilities','MultiUtilities','Minneapolis, Minnesota','New York Stock Exchange','http://www.xcelenergy.com','Xcel Energy Inc., through its subsidiaries, generates, purchases, transmits, distributes, and sells electricity.',44.9796,-93.2705,NULL);
INSERT INTO `companies` VALUES ('XOM','Exxon Mobil Corp.','Energy','Integrated Oil & Gas','Irving, Texas','New York Stock Exchange','http://www.exxonmobil.com','Exxon Mobil Corporation explores for and produces crude oil and natural gas in the United States, Canada/other Americas, Europe, Africa, Asia, and Australia/Oceania.',32.89,-96.9498,'{\"years\":[2019,2018,2017],\"revenue\":[255583000,279332000,237162000],\"earnings\":[14340000,20840000,19710000],\"assets\":[362597000,346196000,348691000],\"liabilities\":[163659000,147668000,154191000]}');
INSERT INTO `companies` VALUES ('XRAY','Dentsply Sirona','Health Care','Health Care Supplies','York, Pennsylvania','New York Stock Exchange','http://www.dentsplysirona.com','DENTSPLY SIRONA Inc. designs, develops, manufactures, and markets various dental products and technologies, and other consumable dental products and equipment primarily for the professional dental market worldwide.',35.0607,-80.8456,NULL);
INSERT INTO `companies` VALUES ('YUM','Yum! Brands Inc','Consumer Discretionary','Restaurants','Louisville, Kentucky','New York Stock Exchange','http://www.yum.com','YUM! Brands, Inc., together with its subsidiaries, develops, operates, and franchises quick service restaurants worldwide.',38.1981,-85.6958,NULL);
INSERT INTO `companies` VALUES ('ZION','Zions Bancorp','Financials','Regional Banks','Salt Lake City, Utah','Nasdaq Global Select','http://www.zionsbancorporation.com','Zions Bancorporation, National Association provides various banking and related services primarily in Arizona, California, Colorado, Idaho, Nevada, New Mexico, Oregon, Texas, Utah, Washington, and Wyoming. ',40.769,-111.89,'{\"years\":[2019,2018,2017],\"revenue\":[2834000,2782000,2609000],\"earnings\":[816000,884000,592000],\"assets\":[69172000,68746000,66288000],\"liabilities\":[61819000,61168000,58609000]}');
INSERT INTO `companies` VALUES ('PSO','Pearson Plc','Communication Services','Publishing','London, UK','London Stock Exchange','http://www.pearson.com','Pearson plc provides educational products and services to governments, educational institutions, corporations, and professional bodies worldwide.',51.5099,-0.121424,'{\"years\":[2019,2018,2017],\"revenue\":[3869000,4129000,4513000],\"earnings\":[264000,588000,406000],\"assets\":[7650000,7905000,7888000],\"liabilities\":[3327000,3380000,3867000]}');

UNLOCK TABLES;
